config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "recommended_foods#index"
  resources :recommended_foods
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recommended_food.rb
class RecommendedFood < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_many :recommended_foods, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/recommended_foods_controller.rb
class RecommendedFoodsController < ApplicationController
  before_action :set_food, only: %i[edit update destroy]

  def index
    @foods = RecommendedFood.includes(:user).order(:created_at)
  end

  def new
    @recommended_food = RecommendedFood.new
  end

  def create
    recommended_food = current_user.recommended_foods.create!(food_params)
    redirect_to recommended_food
  end

  def show
    @recommended_food = RecommendedFood.find(params[:id])
  end

  def edit; end

  def update
    @recommended_food.update!(food_params)
    redirect_to @recommended_food
  end

  def destroy
    @recommended_food.destroy
    redirect_to root_path
  end

  private

  def food_params
    params.require(:recommended_food).permit(:name, :comment, :image)
  end

  def set_food
    @recommended_food = current_user.recommended_foods.find_by(id: params[:id])
    redirect_to root_path, alert: "権限がありません" if @recommended_food.nil?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
  <%= link_to "一覧ページ", root_path %>
  <%= link_to "新規投稿ページ", new_recommended_food_path %>
  <%= link_to "アカウント編集", edit_user_registration_path %>
  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { confirm: "ログアウトしますか？"} %>
  <%= "【ログイン中のアドレス】#{current_user.email}" %>
<% else %>
  <%= link_to "新規登録", new_user_registration_path %>
  <%= link_to "ログイン", new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecommendedFoodApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render "layouts/header" %>
    </header>
    <hr>
    <%= yield %>
  </body>
</html>

app/views/recommended_foods/_food.html.erb
<div>
  <p>【メールアドレス】<%= food.user.email %></p>
  <p>【料理名】<%= food.name %></p>
  <p>
    <%= link_to "詳細", recommended_food_path(food) %>
    <% if current_user.id == food.user_id %>
      <%= link_to "編集", edit_recommended_food_path(food) %>
      <%= link_to "削除", recommended_food_path(food), method: :delete, data: { confirm: "削除しますか?" } %>
    <% end %>
  </p>
</div>
<hr>

app/views/recommended_foods/_form.html.erb
<%= form_with model: @recommended_food, local: true do |form| %>
  <div>
    <p>料理名<%= form.text_field :name, required: true %></p>
    <p><%= form.file_field :image, accept: "image/png,image/jpeg,image/gif" %></p>
    <p>コメント<%= form.text_area :comment %></p>
    <p><%= form.submit "送信" %></p>
  </div>
<% end %>

app/views/recommended_foods/edit.html.erb
<h1>編集</h1>
<%= render "form" %>

app/views/recommended_foods/index.html.erb
<h1>お勧め料理 投稿一覧</h1>
<%= render partial: 'recommended_foods/food', collection: @foods %>

app/views/recommended_foods/new.html.erb
<h1>新規投稿</h1>
<%= render "form" %>

app/views/recommended_foods/show.html.erb
<h1>投稿詳細</h1>
  <p>【メールアドレス】<%= @recommended_food.user.email %></p>
  <p>【料理名】<%= @recommended_food.name %></p>
  <% if @recommended_food.image? %>
    <p><%= image_tag @recommended_food.image.url %></p>
  <% end %>
  <p>【コメント】<%= simple_format(@recommended_food.comment) %></p>
  <% if current_user.id == @recommended_food.user_id %>
  <p>
    <%= link_to "編集", edit_recommended_food_path(@recommended_food) %>
    <%= link_to "削除", recommended_food_path(@recommended_food), method: :delete, data: { confirm: "削除しますか?" } %>
  </p>
  <% end %>
  <p><%= link_to "投稿一覧へ", root_path %></p>
<hr>